//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWmapper_DS4Driver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWmapper_DS4Driver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BumperLeft {
            get {
                object obj = ResourceManager.GetObject("BumperLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BumperRight {
            get {
                object obj = ResourceManager.GetObject("BumperRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CenterLeft {
            get {
                object obj = ResourceManager.GetObject("CenterLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CenterMiddle {
            get {
                object obj = ResourceManager.GetObject("CenterMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CenterRight {
            get {
                object obj = ResourceManager.GetObject("CenterRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Command_Reset_24 {
            get {
                object obj = ResourceManager.GetObject("Command_Reset_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dualshock4 {
            get {
                object obj = ResourceManager.GetObject("Dualshock4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gear39 {
            get {
                object obj = ResourceManager.GetObject("gear39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LFaceDown {
            get {
                object obj = ResourceManager.GetObject("LFaceDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LFaceLeft {
            get {
                object obj = ResourceManager.GetObject("LFaceLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LFaceRight {
            get {
                object obj = ResourceManager.GetObject("LFaceRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LFaceUp {
            get {
                object obj = ResourceManager.GetObject("LFaceUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RFaceDown {
            get {
                object obj = ResourceManager.GetObject("RFaceDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RFaceLeft {
            get {
                object obj = ResourceManager.GetObject("RFaceLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RFaceRight {
            get {
                object obj = ResourceManager.GetObject("RFaceRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RFaceUp {
            get {
                object obj = ResourceManager.GetObject("RFaceUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StickLeft {
            get {
                object obj = ResourceManager.GetObject("StickLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StickRight {
            get {
                object obj = ResourceManager.GetObject("StickRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string STRING_BIND_CAMERA {
            get {
                return ResourceManager.GetString("STRING_BIND_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string STRING_BIND_CANCEL {
            get {
                return ResourceManager.GetString("STRING_BIND_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to change a binding.
        /// </summary>
        internal static string STRING_BIND_HOW {
            get {
                return ResourceManager.GetString("STRING_BIND_HOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid keybind.
        /// </summary>
        internal static string STRING_BIND_ILLEGAL {
            get {
                return ResourceManager.GetString("STRING_BIND_ILLEGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve.
        /// </summary>
        internal static string STRING_BIND_MOUSE_CURVE {
            get {
                return ResourceManager.GetString("STRING_BIND_MOUSE_CURVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadzone.
        /// </summary>
        internal static string STRING_BIND_MOUSE_DEADZONE {
            get {
                return ResourceManager.GetString("STRING_BIND_MOUSE_DEADZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string STRING_BIND_MOUSE_SPEED {
            get {
                return ResourceManager.GetString("STRING_BIND_MOUSE_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the upper touchpad to toggle mouse control.
        /// </summary>
        internal static string STRING_BIND_MOUSE_TOGGLE {
            get {
                return ResourceManager.GetString("STRING_BIND_MOUSE_TOGGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        internal static string STRING_BIND_MOVEMENT {
            get {
                return ResourceManager.GetString("STRING_BIND_MOVEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your keybinds will be reset default.
        ///Are you sure?.
        /// </summary>
        internal static string STRING_BIND_RESET_ALL {
            get {
                return ResourceManager.GetString("STRING_BIND_RESET_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string STRING_BIND_SAVE {
            get {
                return ResourceManager.GetString("STRING_BIND_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the new key for {0}.
        /// </summary>
        internal static string STRING_BIND_SET {
            get {
                return ResourceManager.GetString("STRING_BIND_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set trigger sensitivity.
        /// </summary>
        internal static string STRING_BIND_SET_TRIGGER {
            get {
                return ResourceManager.GetString("STRING_BIND_SET_TRIGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share/Options.
        /// </summary>
        internal static string STRING_BIND_TOUCH_EMULATE {
            get {
                return ResourceManager.GetString("STRING_BIND_TOUCH_EMULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Buttons.
        /// </summary>
        internal static string STRING_BIND_TOUCH_EXTRA {
            get {
                return ResourceManager.GetString("STRING_BIND_TOUCH_EXTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchpad Mode.
        /// </summary>
        internal static string STRING_BIND_TOUCH_MODE {
            get {
                return ResourceManager.GetString("STRING_BIND_TOUCH_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Control.
        /// </summary>
        internal static string STRING_BIND_TOUCH_MOUSE {
            get {
                return ResourceManager.GetString("STRING_BIND_TOUCH_MOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerLeft {
            get {
                object obj = ResourceManager.GetObject("TriggerLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TriggerRight {
            get {
                object obj = ResourceManager.GetObject("TriggerRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
