//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS4ConsolePort.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DS4ConsolePort.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BT {
            get {
                object obj = ResourceManager.GetObject("BT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Circle {
            get {
                object obj = ResourceManager.GetObject("Circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cogs {
            get {
                object obj = ResourceManager.GetObject("cogs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CONSOLEPORTLOGO {
            get {
                object obj = ResourceManager.GetObject("CONSOLEPORTLOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cross {
            get {
                object obj = ResourceManager.GetObject("Cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DPad {
            get {
                object obj = ResourceManager.GetObject("DPad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DPadAll {
            get {
                object obj = ResourceManager.GetObject("DPadAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DpadDown {
            get {
                object obj = ResourceManager.GetObject("DpadDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DPadLeft {
            get {
                object obj = ResourceManager.GetObject("DPadLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DPadLeftRight {
            get {
                object obj = ResourceManager.GetObject("DPadLeftRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DPadRight {
            get {
                object obj = ResourceManager.GetObject("DPadRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DPadUp {
            get {
                object obj = ResourceManager.GetObject("DPadUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DPadUpDown {
            get {
                object obj = ResourceManager.GetObject("DPadUpDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4 {
            get {
                object obj = ResourceManager.GetObject("DS4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DS4_Config {
            get {
                object obj = ResourceManager.GetObject("DS4_Config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap L1 {
            get {
                object obj = ResourceManager.GetObject("L1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap L2 {
            get {
                object obj = ResourceManager.GetObject("L2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LStick {
            get {
                object obj = ResourceManager.GetObject("LStick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LStick_All {
            get {
                object obj = ResourceManager.GetObject("LStick_All", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LStickDown {
            get {
                object obj = ResourceManager.GetObject("LStickDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LStickLeft {
            get {
                object obj = ResourceManager.GetObject("LStickLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LStickRight {
            get {
                object obj = ResourceManager.GetObject("LStickRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LStickUp {
            get {
                object obj = ResourceManager.GetObject("LStickUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LStickX {
            get {
                object obj = ResourceManager.GetObject("LStickX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LStickY {
            get {
                object obj = ResourceManager.GetObject("LStickY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PS {
            get {
                object obj = ResourceManager.GetObject("PS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap R1 {
            get {
                object obj = ResourceManager.GetObject("R1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap R2 {
            get {
                object obj = ResourceManager.GetObject("R2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reset_Binds {
            get {
                object obj = ResourceManager.GetObject("Reset_Binds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RStick {
            get {
                object obj = ResourceManager.GetObject("RStick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RStickAll {
            get {
                object obj = ResourceManager.GetObject("RStickAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RStickDown {
            get {
                object obj = ResourceManager.GetObject("RStickDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RStickLeft {
            get {
                object obj = ResourceManager.GetObject("RStickLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RStickRight {
            get {
                object obj = ResourceManager.GetObject("RStickRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RStickUp {
            get {
                object obj = ResourceManager.GetObject("RStickUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RStickX {
            get {
                object obj = ResourceManager.GetObject("RStickX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RStickY {
            get {
                object obj = ResourceManager.GetObject("RStickY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Share {
            get {
                object obj = ResourceManager.GetObject("Share", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Square {
            get {
                object obj = ResourceManager.GetObject("Square", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string STRING_BIND_CAMERA {
            get {
                return ResourceManager.GetString("STRING_BIND_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        internal static string STRING_BIND_MOVEMENT {
            get {
                return ResourceManager.GetString("STRING_BIND_MOVEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to change binding.
        /// </summary>
        internal static string STRING_BINDING_CHANGE {
            get {
                return ResourceManager.GetString("STRING_BINDING_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already bound to {1}!.
        /// </summary>
        internal static string STRING_BINDING_EXISTS {
            get {
                return ResourceManager.GetString("STRING_BINDING_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid keybind!.
        /// </summary>
        internal static string STRING_BINDING_ILLEGAL {
            get {
                return ResourceManager.GetString("STRING_BINDING_ILLEGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the keyboard key for {0}.
        /// </summary>
        internal static string STRING_BINDING_SET {
            get {
                return ResourceManager.GetString("STRING_BINDING_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string STRING_CANCEL {
            get {
                return ResourceManager.GetString("STRING_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        internal static string STRING_COLOR_CRIT {
            get {
                return ResourceManager.GetString("STRING_COLOR_CRIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string STRING_COLOR_HIGH {
            get {
                return ResourceManager.GetString("STRING_COLOR_HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string STRING_COLOR_LOW {
            get {
                return ResourceManager.GetString("STRING_COLOR_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string STRING_COLOR_MED {
            get {
                return ResourceManager.GetString("STRING_COLOR_MED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected ({0}%).
        /// </summary>
        internal static string STRING_CONTROLLER_CONNECTED {
            get {
                return ResourceManager.GetString("STRING_CONTROLLER_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string STRING_CONTROLLER_DISCONNECTED {
            get {
                return ResourceManager.GetString("STRING_CONTROLLER_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsolePort successfully updated to version {0}..
        /// </summary>
        internal static string STRING_CP_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("STRING_CP_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS4ConsolePort successfully updated to version {0}..
        /// </summary>
        internal static string STRING_DS4_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("STRING_DS4_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS4C Settings.
        /// </summary>
        internal static string STRING_DS4CSETTINGS {
            get {
                return ResourceManager.GetString("STRING_DS4CSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow the cursor when over an object.
        /// </summary>
        internal static string STRING_ENABLE_STICKY_CURSOR {
            get {
                return ResourceManager.GetString("STRING_ENABLE_STICKY_CURSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find WoW.
        /// </summary>
        internal static string STRING_FIND_WOW {
            get {
                return ResourceManager.GetString("STRING_FIND_WOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DualShock4 Status.
        /// </summary>
        internal static string STRING_GROUP_DS4_STATUS {
            get {
                return ResourceManager.GetString("STRING_GROUP_DS4_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoW Installation Folder.
        /// </summary>
        internal static string STRING_GROUP_WOW_PATH {
            get {
                return ResourceManager.GetString("STRING_GROUP_WOW_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced haptics attached.
        /// </summary>
        internal static string STRING_HAPTIC_ATTACHED {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_ATTACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character logged in.
        /// </summary>
        internal static string STRING_HAPTIC_CHARLOGGEDIN {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_CHARLOGGEDIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Advanced Haptics.
        /// </summary>
        internal static string STRING_HAPTIC_ENABLE {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Lightbar by class.
        /// </summary>
        internal static string STRING_HAPTIC_LBCLASS {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_LBCLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Lightbar by health.
        /// </summary>
        internal static string STRING_HAPTIC_LBHEALTH {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_LBHEALTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate on damage taken.
        /// </summary>
        internal static string STRING_HAPTIC_RUMBLEDAMAGE {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_RUMBLEDAMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate when switching targets.
        /// </summary>
        internal static string STRING_HAPTIC_RUMBLETARGET {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_RUMBLETARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Haptics.
        /// </summary>
        internal static string STRING_HAPTIC_SETTINGS {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haptic Status.
        /// </summary>
        internal static string STRING_HAPTIC_STATUS {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced haptics was disabled because there was an error loading the module..
        /// </summary>
        internal static string STRING_HAPTICS_DISABLED_ERROR {
            get {
                return ResourceManager.GetString("STRING_HAPTICS_DISABLED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced haptics was disabled because there are no offsets available for your version..
        /// </summary>
        internal static string STRING_HAPTICS_DISABLED_NO_OFFSETS {
            get {
                return ResourceManager.GetString("STRING_HAPTICS_DISABLED_NO_OFFSETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightbar Settings.
        /// </summary>
        internal static string STRING_HAPTICS_LB_SETTINGS {
            get {
                return ResourceManager.GetString("STRING_HAPTICS_LB_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration Settings.
        /// </summary>
        internal static string STRING_HAPTICS_RUMBLE_SETTINGS {
            get {
                return ResourceManager.GetString("STRING_HAPTICS_RUMBLE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string STRING_INSTALL_BUTTON {
            get {
                return ResourceManager.GetString("STRING_INSTALL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction.
        /// </summary>
        internal static string STRING_INTERACTION {
            get {
                return ResourceManager.GetString("STRING_INTERACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string STRING_INTERACTION_SETTINGS {
            get {
                return ResourceManager.GetString("STRING_INTERACTION_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash lightbar when battery low.
        /// </summary>
        internal static string STRING_LB_BATTERY {
            get {
                return ResourceManager.GetString("STRING_LB_BATTERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string STRING_MISC {
            get {
                return ResourceManager.GetString("STRING_MISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate your World of Warcraft installation folder. This is required for some features.
        ///
        ///Would you like to find your WoW folder now?.
        /// </summary>
        internal static string STRING_NO_WOW_PATH {
            get {
                return ResourceManager.GetString("STRING_NO_WOW_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string STRING_NOTIFY_MENU_EXIT {
            get {
                return ResourceManager.GetString("STRING_NOTIFY_MENU_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS4ConsolePort.
        /// </summary>
        internal static string STRING_NOTIFY_TOOLTIP {
            get {
                return ResourceManager.GetString("STRING_NOTIFY_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string STRING_SAVE {
            get {
                return ResourceManager.GetString("STRING_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to tray.
        /// </summary>
        internal static string STRING_SETTING_CLOSE_TRAY {
            get {
                return ResourceManager.GetString("STRING_SETTING_CLOSE_TRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haptics.
        /// </summary>
        internal static string STRING_SETTING_HAPTICS {
            get {
                return ResourceManager.GetString("STRING_SETTING_HAPTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable when WoW not running.
        /// </summary>
        internal static string STRING_SETTING_INPUT_BGDISABLE {
            get {
                return ResourceManager.GetString("STRING_SETTING_INPUT_BGDISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send keystrokes directly to WoW.
        /// </summary>
        internal static string STRING_SETTING_KEY_DIRECT {
            get {
                return ResourceManager.GetString("STRING_SETTING_KEY_DIRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        internal static string STRING_SETTING_MIN_TRAY {
            get {
                return ResourceManager.GetString("STRING_SETTING_MIN_TRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mouse clicks directly to WoW.
        /// </summary>
        internal static string STRING_SETTING_MOUSE_DIRECT {
            get {
                return ResourceManager.GetString("STRING_SETTING_MOUSE_DIRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized.
        /// </summary>
        internal static string STRING_SETTING_START_MINIMIZED {
            get {
                return ResourceManager.GetString("STRING_SETTING_START_MINIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string STRING_TAB_ADVANCED {
            get {
                return ResourceManager.GetString("STRING_TAB_ADVANCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsolePort.
        /// </summary>
        internal static string STRING_TAB_CONSOLEPORT {
            get {
                return ResourceManager.GetString("STRING_TAB_CONSOLEPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybinds.
        /// </summary>
        internal static string STRING_TAB_KEYBINDS {
            get {
                return ResourceManager.GetString("STRING_TAB_KEYBINDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the keybindings to default.
        /// </summary>
        internal static string STRING_TOOLTIP_RESET_BINDS {
            get {
                return ResourceManager.GetString("STRING_TOOLTIP_RESET_BINDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TouchLeft/Right.
        /// </summary>
        internal static string STRING_TOUCHPAD_BUTTONS {
            get {
                return ResourceManager.GetString("STRING_TOUCHPAD_BUTTONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchpad Mode.
        /// </summary>
        internal static string STRING_TOUCHPAD_MODE {
            get {
                return ResourceManager.GetString("STRING_TOUCHPAD_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Control.
        /// </summary>
        internal static string STRING_TOUCHPAD_MOUSE {
            get {
                return ResourceManager.GetString("STRING_TOUCHPAD_MOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share/Options.
        /// </summary>
        internal static string STRING_TOUCHPAD_SHARE_OPTIONS {
            get {
                return ResourceManager.GetString("STRING_TOUCHPAD_SHARE_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the desired trigger sensitivity.
        /// </summary>
        internal static string STRING_TRIGGERS_ADJUST {
            get {
                return ResourceManager.GetString("STRING_TRIGGERS_ADJUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string STRING_UPDATE_BUTTON {
            get {
                return ResourceManager.GetString("STRING_UPDATE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update file is being downloaded and will be automatically installed when the download is complete. Please wait....
        /// </summary>
        internal static string STRING_UPDATE_TEXT {
            get {
                return ResourceManager.GetString("STRING_UPDATE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your keybindings will be reset to default. Are you sure?.
        /// </summary>
        internal static string STRING_WARN_RESET_BINDS {
            get {
                return ResourceManager.GetString("STRING_WARN_RESET_BINDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Haptics.
        /// </summary>
        internal static string STRING_WINDOW_ADVANCED_HAPTICS {
            get {
                return ResourceManager.GetString("STRING_WINDOW_ADVANCED_HAPTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close World of Warcraft before updating..
        /// </summary>
        internal static string STRING_WOW_RUNNING_CLOSE {
            get {
                return ResourceManager.GetString("STRING_WOW_RUNNING_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoW window found.
        /// </summary>
        internal static string STRING_WOW_WINDOW_FOUND {
            get {
                return ResourceManager.GetString("STRING_WOW_WINDOW_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TouchLeft {
            get {
                object obj = ResourceManager.GetObject("TouchLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TouchRight {
            get {
                object obj = ResourceManager.GetObject("TouchRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Triangle {
            get {
                object obj = ResourceManager.GetObject("Triangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap USB {
            get {
                object obj = ResourceManager.GetObject("USB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon WoWConsolePort {
            get {
                object obj = ResourceManager.GetObject("WoWConsolePort", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
