//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWmapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWmapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English translation by Topher Sheridan.
        /// </summary>
        public static string AboutTranslationCredit {
            get {
                return ResourceManager.GetString("AboutTranslationCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Features.
        /// </summary>
        public static string AdvancedFeaturesHeader {
            get {
                return ResourceManager.GetString("AdvancedFeaturesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These options will have no effect unless advanced features are enabled.
        /// </summary>
        public static string AdvancedFeaturesRequired {
            get {
                return ResourceManager.GetString("AdvancedFeaturesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling this option allows WoWmapper to read certain values from the game&apos;s memory, such as your character&apos;s level, health and target.
        ///
        ///Accessing the game in this manner may be a violation of the World of Warcraft Terms of Use. For more information, please visit the link below..
        /// </summary>
        public static string AdvancedFeaturesWarning {
            get {
                return ResourceManager.GetString("AdvancedFeaturesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        public static string AdvancedMoreInfo {
            get {
                return ResourceManager.GetString("AdvancedMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string AppearanceAccent {
            get {
                return ResourceManager.GetString("AppearanceAccent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color window automatically by class.
        /// </summary>
        public static string AppearanceColorByClass {
            get {
                return ResourceManager.GetString("AppearanceColorByClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable drop shadow.
        /// </summary>
        public static string AppearanceDropShadow {
            get {
                return ResourceManager.GetString("AppearanceDropShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string AppearanceLanguage {
            get {
                return ResourceManager.GetString("AppearanceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting will be applied the next time you start WoWmapper.
        /// </summary>
        public static string AppearanceRestartApp {
            get {
                return ResourceManager.GetString("AppearanceRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string AppearanceTheme {
            get {
                return ResourceManager.GetString("AppearanceTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WoWmapper.
        /// </summary>
        public static string ButtonAboutWowmapper {
            get {
                return ResourceManager.GetString("ButtonAboutWowmapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string CommonLeft {
            get {
                return ResourceManager.GetString("CommonLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string CommonRight {
            get {
                return ResourceManager.GetString("CommonRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string ControllersActivate {
            get {
                return ResourceManager.GetString("ControllersActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically activate controller.
        /// </summary>
        public static string ControllersAutoSelect {
            get {
                return ResourceManager.GetString("ControllersAutoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller {0}.
        /// </summary>
        public static string ControllersControllerNumber {
            get {
                return ResourceManager.GetString("ControllersControllerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Controllers.
        /// </summary>
        public static string ControllersDetected {
            get {
                return ResourceManager.GetString("ControllersDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable DualShock 4.
        /// </summary>
        public static string ControllersEnableDs4 {
            get {
                return ResourceManager.GetString("ControllersEnableDs4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Xbox Controller.
        /// </summary>
        public static string ControllersEnableXbox {
            get {
                return ResourceManager.GetString("ControllersEnableXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-scan.
        /// </summary>
        public static string ControllersScan {
            get {
                return ResourceManager.GetString("ControllersScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Stick/Cursor.
        /// </summary>
        public static string CursorAnalogStick {
            get {
                return ResourceManager.GetString("CursorAnalogStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel mouselook on alt-tab.
        /// </summary>
        public static string CursorAutoCancel {
            get {
                return ResourceManager.GetString("CursorAutoCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-center cursor after mouselook.
        /// </summary>
        public static string CursorAutoCenter {
            get {
                return ResourceManager.GetString("CursorAutoCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert camera horizontal (X) axis.
        /// </summary>
        public static string CursorCameraInvertHorizontal {
            get {
                return ResourceManager.GetString("CursorCameraInvertHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert camera vertical (Y) axis.
        /// </summary>
        public static string CursorCameraInvertVertical {
            get {
                return ResourceManager.GetString("CursorCameraInvertVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve.
        /// </summary>
        public static string CursorCurve {
            get {
                return ResourceManager.GetString("CursorCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadzone.
        /// </summary>
        public static string CursorDeadzone {
            get {
                return ResourceManager.GetString("CursorDeadzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string CursorSpeed {
            get {
                return ResourceManager.GetString("CursorSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchpad.
        /// </summary>
        public static string CursorTouchpad {
            get {
                return ResourceManager.GetString("CursorTouchpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchpad mode.
        /// </summary>
        public static string CursorTouchpadMode {
            get {
                return ResourceManager.GetString("CursorTouchpadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Buttons.
        /// </summary>
        public static string CursorTouchpadModeButtons {
            get {
                return ResourceManager.GetString("CursorTouchpadModeButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share &amp; Options.
        /// </summary>
        public static string CursorTouchpadModeEmulateCenter {
            get {
                return ResourceManager.GetString("CursorTouchpadModeEmulateCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Control.
        /// </summary>
        public static string CursorTouchpadModeMouse {
            get {
                return ResourceManager.GetString("CursorTouchpadModeMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto toggle walk/run when moving.
        /// </summary>
        public static string CursorWalkEnable {
            get {
                return ResourceManager.GetString("CursorWalkEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk/Run Hotkey.
        /// </summary>
        public static string CursorWalkHotkey {
            get {
                return ResourceManager.GetString("CursorWalkHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        public static string CursorWalkThreshold {
            get {
                return ResourceManager.GetString("CursorWalkThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By continuing you acknowledge that you have read and understand the risks associated with this feature..
        /// </summary>
        public static string DialogAdvancedFeaturesWarningText {
            get {
                return ResourceManager.GetString("DialogAdvancedFeaturesWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DialogAdvancedFeaturesWarningTitle {
            get {
                return ResourceManager.GetString("DialogAdvancedFeaturesWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the new key for {0}. Existing keys will be swapped..
        /// </summary>
        public static string DialogBindKeyText {
            get {
                return ResourceManager.GetString("DialogBindKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Binding.
        /// </summary>
        public static string DialogBindKeyTitle {
            get {
                return ResourceManager.GetString("DialogBindKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating ConsolePort:
        ///{0}.
        /// </summary>
        public static string DialogConsolePortUpdateFailedText {
            get {
                return ResourceManager.GetString("DialogConsolePortUpdateFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsolePort was successfully updated!.
        /// </summary>
        public static string DialogConsolePortUpdateSuccessText {
            get {
                return ResourceManager.GetString("DialogConsolePortUpdateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsolePort Update.
        /// </summary>
        public static string DialogConsoleportUpdateTitle {
            get {
                return ResourceManager.GetString("DialogConsoleportUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File download in progress, please wait....
        /// </summary>
        public static string DialogDownloadingText {
            get {
                return ResourceManager.GetString("DialogDownloadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string DialogDownloadingTitle {
            get {
                return ResourceManager.GetString("DialogDownloadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error downloading the file, please try again later..
        /// </summary>
        public static string DialogErrorDownloadFailedText {
            get {
                return ResourceManager.GetString("DialogErrorDownloadFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        public static string DialogErrorDownloadFailedTitle {
            get {
                return ResourceManager.GetString("DialogErrorDownloadFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, the left and right triggers will activate an extra binding when they reach a certain point. With the triggers as Shift or Control, you can use a full trigger press to activate an extra binding..
        /// </summary>
        public static string DialogHelpTriggerGripText {
            get {
                return ResourceManager.GetString("DialogHelpTriggerGripText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Grip Binding.
        /// </summary>
        public static string DialogHelpTriggerGripTitle {
            get {
                return ResourceManager.GetString("DialogHelpTriggerGripTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you selected does not appear to contain valid keybind data..
        /// </summary>
        public static string DialogInvalidKeybindFileText {
            get {
                return ResourceManager.GetString("DialogInvalidKeybindFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file.
        /// </summary>
        public static string DialogInvalidKeybindFileTitle {
            get {
                return ResourceManager.GetString("DialogInvalidKeybindFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of World of Warcraft is not currently supported by WoWmapper. Please check for an update and try again..
        /// </summary>
        public static string DialogNoOffsetsFoundText {
            get {
                return ResourceManager.GetString("DialogNoOffsetsFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offsets outdated.
        /// </summary>
        public static string DialogNoOffsetsFoundTitle {
            get {
                return ResourceManager.GetString("DialogNoOffsetsFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete all WoWmapper settings and keybinds and exit the program. Are you sure you want to continue?.
        /// </summary>
        public static string DialogResetAllText {
            get {
                return ResourceManager.GetString("DialogResetAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings.
        /// </summary>
        public static string DialogResetAllTitle {
            get {
                return ResourceManager.GetString("DialogResetAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select your World of Warcraft installation directory first..
        /// </summary>
        public static string DialogSelectWoWFirstText {
            get {
                return ResourceManager.GetString("DialogSelectWoWFirstText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoW not found.
        /// </summary>
        public static string DialogSelectWoWFirstTitle {
            get {
                return ResourceManager.GetString("DialogSelectWoWFirstTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select WoW installation folder.
        /// </summary>
        public static string DialogWoWFolderBrowserTitle {
            get {
                return ResourceManager.GetString("DialogWoWFolderBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate your World of Warcraft installation! Would you like to specify a location now?.
        /// </summary>
        public static string DialogWoWNotFoundText {
            get {
                return ResourceManager.GetString("DialogWoWNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh oh!.
        /// </summary>
        public static string DialogWoWNotFoundTitle {
            get {
                return ResourceManager.GetString("DialogWoWNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you selected does not appear to contain World of Warcraft..
        /// </summary>
        public static string ErrorDialogInvalidFolderText {
            get {
                return ResourceManager.GetString("ErrorDialogInvalidFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder.
        /// </summary>
        public static string ErrorDialogInvalidFolderTitle {
            get {
                return ResourceManager.GetString("ErrorDialogInvalidFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver disabled.
        /// </summary>
        public static string ErrorDriverDisabledTitle {
            get {
                return ResourceManager.GetString("ErrorDriverDisabledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with the DS4 driver, and it has been disabled.
        ///
        ///The error was:
        ///{0}.
        /// </summary>
        public static string ErrorDriverDs4Disabled {
            get {
                return ResourceManager.GetString("ErrorDriverDs4Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with the Xbox driver, and it has been disabled.
        ///
        ///The error was:
        ///{0}.
        /// </summary>
        public static string ErrorDriverXboxDisabled {
            get {
                return ResourceManager.GetString("ErrorDriverXboxDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string HapticsBasic {
            get {
                return ResourceManager.GetString("HapticsBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash lightbar at .
        /// </summary>
        public static string HapticsFlashBatteryLow {
            get {
                return ResourceManager.GetString("HapticsFlashBatteryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color lightbar.
        /// </summary>
        public static string HapticsLightbarColor {
            get {
                return ResourceManager.GetString("HapticsLightbarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical (less than 20%).
        /// </summary>
        public static string HealthLevelCritical {
            get {
                return ResourceManager.GetString("HealthLevelCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High (more than 90%).
        /// </summary>
        public static string HealthLevelHigh {
            get {
                return ResourceManager.GetString("HealthLevelHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low (more than 20%).
        /// </summary>
        public static string HealthLevelLow {
            get {
                return ResourceManager.GetString("HealthLevelLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium (more than 50%).
        /// </summary>
        public static string HealthLevelMedium {
            get {
                return ResourceManager.GetString("HealthLevelMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string KeybindsExport {
            get {
                return ResourceManager.GetString("KeybindsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string KeybindsImport {
            get {
                return ResourceManager.GetString("KeybindsImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Keybinds.
        /// </summary>
        public static string KeybindsReset {
            get {
                return ResourceManager.GetString("KeybindsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color lightbar by remaining health.
        /// </summary>
        public static string LightbarByRemainingHealth {
            get {
                return ResourceManager.GetString("LightbarByRemainingHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color lightbar with class color.
        /// </summary>
        public static string LightbarWithClassColor {
            get {
                return ResourceManager.GetString("LightbarWithClassColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging... [{0}%].
        /// </summary>
        public static string MainWindowBatteryCharging {
            get {
                return ResourceManager.GetString("MainWindowBatteryCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string MainWindowBatteryConnected {
            get {
                return ResourceManager.GetString("MainWindowBatteryConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharging... [{0}%].
        /// </summary>
        public static string MainWindowBatteryDischarging {
            get {
                return ResourceManager.GetString("MainWindowBatteryDischarging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string MainWindowControllerBatteryNotConnected {
            get {
                return ResourceManager.GetString("MainWindowControllerBatteryNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Connected.
        /// </summary>
        public static string MainWindowControllerConnected {
            get {
                return ResourceManager.GetString("MainWindowControllerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active controller.
        /// </summary>
        public static string MainWindowControllerNotActive {
            get {
                return ResourceManager.GetString("MainWindowControllerNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Status.
        /// </summary>
        public static string MainWindowControllerTitle {
            get {
                return ResourceManager.GetString("MainWindowControllerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindowSettingsButton {
            get {
                return ResourceManager.GetString("MainWindowSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoWmapper.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Updates.
        /// </summary>
        public static string MainWindowUpdateTitle {
            get {
                return ResourceManager.GetString("MainWindowUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        public static string MainWindowVersionChecking {
            get {
                return ResourceManager.GetString("MainWindowVersionChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is available!.
        /// </summary>
        public static string MainWindowVersionConsoleportAvailable {
            get {
                return ResourceManager.GetString("MainWindowVersionConsoleportAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsolePort {0}.
        /// </summary>
        public static string MainWindowVersionConsoleportCurrent {
            get {
                return ResourceManager.GetString("MainWindowVersionConsoleportCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsolePort is not installed!.
        /// </summary>
        public static string MainWindowVersionConsolePortIsNotInstalled {
            get {
                return ResourceManager.GetString("MainWindowVersionConsolePortIsNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string MainWindowVersionInstall {
            get {
                return ResourceManager.GetString("MainWindowVersionInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new version available.
        /// </summary>
        public static string MainWindowVersionNoNewVersion {
            get {
                return ResourceManager.GetString("MainWindowVersionNoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string MainWindowVersionUpdateButton {
            get {
                return ResourceManager.GetString("MainWindowVersionUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is available!.
        /// </summary>
        public static string MainWindowVersionWowmapperAvailable {
            get {
                return ResourceManager.GetString("MainWindowVersionWowmapperAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoWmapper {0}.
        /// </summary>
        public static string MainWindowVersionWowmapperCurrent {
            get {
                return ResourceManager.GetString("MainWindowVersionWowmapperCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not running/Error.
        /// </summary>
        public static string MainWindowWoWError {
            get {
                return ResourceManager.GetString("MainWindowWoWError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged Out.
        /// </summary>
        public static string MainWindowWoWLoggedOut {
            get {
                return ResourceManager.GetString("MainWindowWoWLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft not running.
        /// </summary>
        public static string MainWindowWoWNotRunning {
            get {
                return ResourceManager.GetString("MainWindowWoWNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft is running (32-bit).
        /// </summary>
        public static string MainWindowWowRunning32 {
            get {
                return ResourceManager.GetString("MainWindowWowRunning32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft is running (64-bit).
        /// </summary>
        public static string MainWindowWoWRunning64 {
            get {
                return ResourceManager.GetString("MainWindowWoWRunning64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft Status.
        /// </summary>
        public static string MainWindowWoWTitle {
            get {
                return ResourceManager.GetString("MainWindowWoWTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controllers.
        /// </summary>
        public static string NotifyMenuControllers {
            get {
                return ResourceManager.GetString("NotifyMenuControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string NotifyMenuExit {
            get {
                return ResourceManager.GetString("NotifyMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybinds.
        /// </summary>
        public static string NotifyMenuKeybinds {
            get {
                return ResourceManager.GetString("NotifyMenuKeybinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open WoWmapper.
        /// </summary>
        public static string NotifyMenuOpenWowmapper {
            get {
                return ResourceManager.GetString("NotifyMenuOpenWowmapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap playstation_24 {
            get {
                object obj = ResourceManager.GetObject("playstation_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WoWmapper.
        /// </summary>
        public static string SettingsAboutTitle {
            get {
                return ResourceManager.GetString("SettingsAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string SettingsAdvanced {
            get {
                return ResourceManager.GetString("SettingsAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string SettingsAdvancedSubItem {
            get {
                return ResourceManager.GetString("SettingsAdvancedSubItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        public static string SettingsAdvancedTitle {
            get {
                return ResourceManager.GetString("SettingsAdvancedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string SettingsAppearance {
            get {
                return ResourceManager.GetString("SettingsAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controllers.
        /// </summary>
        public static string SettingsControllers {
            get {
                return ResourceManager.GetString("SettingsControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Input.
        /// </summary>
        public static string SettingsCursor {
            get {
                return ResourceManager.GetString("SettingsCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Advanced Features.
        /// </summary>
        public static string SettingsEnableAdvancedFeatures {
            get {
                return ResourceManager.GetString("SettingsEnableAdvancedFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haptics.
        /// </summary>
        public static string SettingsHaptics {
            get {
                return ResourceManager.GetString("SettingsHaptics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string SettingsHapticsColors {
            get {
                return ResourceManager.GetString("SettingsHapticsColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        public static string SettingsHapticsVibration {
            get {
                return ResourceManager.GetString("SettingsHapticsVibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string SettingsInput {
            get {
                return ResourceManager.GetString("SettingsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybinds.
        /// </summary>
        public static string SettingsKeybinds {
            get {
                return ResourceManager.GetString("SettingsKeybinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string SettingsPreferences {
            get {
                return ResourceManager.GetString("SettingsPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings.
        /// </summary>
        public static string SettingsResetAll {
            get {
                return ResourceManager.GetString("SettingsResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers.
        /// </summary>
        public static string SettingsTriggers {
            get {
                return ResourceManager.GetString("SettingsTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft.
        /// </summary>
        public static string SettingsWoW {
            get {
                return ResourceManager.GetString("SettingsWoW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoWmapper.
        /// </summary>
        public static string SettingsWoWmapper {
            get {
                return ResourceManager.GetString("SettingsWoWmapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Trigger Grip.
        /// </summary>
        public static string TriggersEnableTriggerGrip {
            get {
                return ResourceManager.GetString("TriggersEnableTriggerGrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Grip Thresholds.
        /// </summary>
        public static string TriggersGripThresholds {
            get {
                return ResourceManager.GetString("TriggersGripThresholds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Thresholds.
        /// </summary>
        public static string TriggersThresholdsBox {
            get {
                return ResourceManager.GetString("TriggersThresholdsBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate when taking damage.
        /// </summary>
        public static string VibrationDamage {
            get {
                return ResourceManager.GetString("VibrationDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate when switching target.
        /// </summary>
        public static string VibrationTarget {
            get {
                return ResourceManager.GetString("VibrationTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate when activating trigger click.
        /// </summary>
        public static string VibrationTriggerGrip {
            get {
                return ResourceManager.GetString("VibrationTriggerGrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32-bit.
        /// </summary>
        public static string WoWArchitecture32 {
            get {
                return ResourceManager.GetString("WoWArchitecture32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64-bit.
        /// </summary>
        public static string WoWArchitecture64 {
            get {
                return ResourceManager.GetString("WoWArchitecture64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Select.
        /// </summary>
        public static string WoWArchitectureAuto {
            get {
                return ResourceManager.GetString("WoWArchitectureAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate Installation Path.
        /// </summary>
        public static string WoWFolderBrowse {
            get {
                return ResourceManager.GetString("WoWFolderBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Architecture.
        /// </summary>
        public static string WoWGameArchitecture {
            get {
                return ResourceManager.GetString("WoWGameArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Path.
        /// </summary>
        public static string WoWInstallationPath {
            get {
                return ResourceManager.GetString("WoWInstallationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon WoWmapper_Icon {
            get {
                object obj = ResourceManager.GetObject("WoWmapper_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to tray.
        /// </summary>
        public static string WoWmapperCloseToTray {
            get {
                return ResourceManager.GetString("WoWmapperCloseToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable debug logging.
        /// </summary>
        public static string WoWmapperEnableLogging {
            get {
                return ResourceManager.GetString("WoWmapperEnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        public static string WoWmapperMinimizeToTray {
            get {
                return ResourceManager.GetString("WoWmapperMinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send keys to foreground window.
        /// </summary>
        public static string WoWmapperSendForegroundKeys {
            get {
                return ResourceManager.GetString("WoWmapperSendForegroundKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized.
        /// </summary>
        public static string WoWmapperStartMinimized {
            get {
                return ResourceManager.GetString("WoWmapperStartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Log File.
        /// </summary>
        public static string WoWmapperViewLog {
            get {
                return ResourceManager.GetString("WoWmapperViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap xbox_24 {
            get {
                object obj = ResourceManager.GetObject("xbox_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
