//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWmapper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWmapper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BT {
            get {
                object obj = ResourceManager.GetObject("BT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoWmapper.
        /// </summary>
        internal static string STRING_APP_NAME {
            get {
                return ResourceManager.GetString("STRING_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string STRING_CANCEL {
            get {
                return ResourceManager.GetString("STRING_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        internal static string STRING_COLOR_CRIT {
            get {
                return ResourceManager.GetString("STRING_COLOR_CRIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string STRING_COLOR_HIGH {
            get {
                return ResourceManager.GetString("STRING_COLOR_HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string STRING_COLOR_LOW {
            get {
                return ResourceManager.GetString("STRING_COLOR_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string STRING_COLOR_MED {
            get {
                return ResourceManager.GetString("STRING_COLOR_MED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} connected ({0}%).
        /// </summary>
        internal static string STRING_CONTROLLER_CONNECTED {
            get {
                return ResourceManager.GetString("STRING_CONTROLLER_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string STRING_CONTROLLER_DISCONNECTED {
            get {
                return ResourceManager.GetString("STRING_CONTROLLER_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find WoW.
        /// </summary>
        internal static string STRING_FIND_WOW {
            get {
                return ResourceManager.GetString("STRING_FIND_WOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string STRING_GROUP_STATUS {
            get {
                return ResourceManager.GetString("STRING_GROUP_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoW Installation Folder.
        /// </summary>
        internal static string STRING_GROUP_WOW_PATH {
            get {
                return ResourceManager.GetString("STRING_GROUP_WOW_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced haptics attached.
        /// </summary>
        internal static string STRING_HAPTIC_ATTACHED {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_ATTACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character logged in.
        /// </summary>
        internal static string STRING_HAPTIC_CHARLOGGEDIN {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_CHARLOGGEDIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color LED/Lightbar.
        /// </summary>
        internal static string STRING_HAPTIC_LED {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_LED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash when battery low.
        /// </summary>
        internal static string STRING_HAPTIC_LED_BATTERY {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_LED_BATTERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color by class.
        /// </summary>
        internal static string STRING_HAPTIC_LED_CLASS {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_LED_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color by remaining health.
        /// </summary>
        internal static string STRING_HAPTIC_LED_HEALTH {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_LED_HEALTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumble.
        /// </summary>
        internal static string STRING_HAPTIC_RUMBLE {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_RUMBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumble when taking damage.
        /// </summary>
        internal static string STRING_HAPTIC_RUMBLE_DAMAGE {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_RUMBLE_DAMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumble when switching target.
        /// </summary>
        internal static string STRING_HAPTIC_RUMBLE_TARGET {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_RUMBLE_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Haptics.
        /// </summary>
        internal static string STRING_HAPTIC_STATUS {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow the cursor when over an object.
        /// </summary>
        internal static string STRING_HAPTIC_STICKY_CURSOR {
            get {
                return ResourceManager.GetString("STRING_HAPTIC_STICKY_CURSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string STRING_INSTALL_BUTTON {
            get {
                return ResourceManager.GetString("STRING_INSTALL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close World of Warcraft before updating..
        /// </summary>
        internal static string STRING_MESSAGE_CLOSE_WOW {
            get {
                return ResourceManager.GetString("STRING_MESSAGE_CLOSE_WOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsolePort successfully updated to version {0}..
        /// </summary>
        internal static string STRING_MESSAGE_CP_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("STRING_MESSAGE_CP_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoWmapper successfully updated to version {0}..
        /// </summary>
        internal static string STRING_MESSAGE_DS4_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("STRING_MESSAGE_DS4_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced haptics was disabled because there was an error loading the module..
        /// </summary>
        internal static string STRING_MESSAGE_HAPTICS_DISABLED_ERROR {
            get {
                return ResourceManager.GetString("STRING_MESSAGE_HAPTICS_DISABLED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced haptics was disabled because there are no offsets available for your version..
        /// </summary>
        internal static string STRING_MESSAGE_HAPTICS_DISABLED_NO_OFFSETS {
            get {
                return ResourceManager.GetString("STRING_MESSAGE_HAPTICS_DISABLED_NO_OFFSETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input plugin selected.
        ///Please select an input plugin before configuring keybindings..
        /// </summary>
        internal static string STRING_MESSAGE_NO_PLUGIN_SELECTED {
            get {
                return ResourceManager.GetString("STRING_MESSAGE_NO_PLUGIN_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate your World of Warcraft installation folder. This is required for some features.
        ///
        ///Would you like to find your WoW folder now?.
        /// </summary>
        internal static string STRING_MESSAGE_NO_WOW_PATH {
            get {
                return ResourceManager.GetString("STRING_MESSAGE_NO_WOW_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string STRING_MISC {
            get {
                return ResourceManager.GetString("STRING_MISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string STRING_NOTIFY_MENU_EXIT {
            get {
                return ResourceManager.GetString("STRING_NOTIFY_MENU_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoWmapper.
        /// </summary>
        internal static string STRING_NOTIFY_TOOLTIP {
            get {
                return ResourceManager.GetString("STRING_NOTIFY_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string STRING_SAVE {
            get {
                return ResourceManager.GetString("STRING_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Preferences.
        /// </summary>
        internal static string STRING_SETTING_APP_PREFS {
            get {
                return ResourceManager.GetString("STRING_SETTING_APP_PREFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to tray.
        /// </summary>
        internal static string STRING_SETTING_CLOSE_TRAY {
            get {
                return ResourceManager.GetString("STRING_SETTING_CLOSE_TRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure advanced haptics.
        /// </summary>
        internal static string STRING_SETTING_CONFIG_ADVANCED_HAPTICS {
            get {
                return ResourceManager.GetString("STRING_SETTING_CONFIG_ADVANCED_HAPTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable when WoW not running.
        /// </summary>
        internal static string STRING_SETTING_DISABLE_WOW_NOT_RUNNING {
            get {
                return ResourceManager.GetString("STRING_SETTING_DISABLE_WOW_NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string STRING_SETTING_DONE {
            get {
                return ResourceManager.GetString("STRING_SETTING_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable advanced haptics.
        /// </summary>
        internal static string STRING_SETTING_ENABLE_ADVANCED_HAPTICS {
            get {
                return ResourceManager.GetString("STRING_SETTING_ENABLE_ADVANCED_HAPTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haptic Settings.
        /// </summary>
        internal static string STRING_SETTING_HAPTIC {
            get {
                return ResourceManager.GetString("STRING_SETTING_HAPTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haptics.
        /// </summary>
        internal static string STRING_SETTING_HAPTICS {
            get {
                return ResourceManager.GetString("STRING_SETTING_HAPTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate WoW.
        /// </summary>
        internal static string STRING_SETTING_LOCATE_WOW {
            get {
                return ResourceManager.GetString("STRING_SETTING_LOCATE_WOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        internal static string STRING_SETTING_MIN_TRAY {
            get {
                return ResourceManager.GetString("STRING_SETTING_MIN_TRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable controller when WoW is not running.
        /// </summary>
        internal static string STRING_SETTING_NO_WOW_DIABLE {
            get {
                return ResourceManager.GetString("STRING_SETTING_NO_WOW_DIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized.
        /// </summary>
        internal static string STRING_SETTING_START_MINIMIZED {
            get {
                return ResourceManager.GetString("STRING_SETTING_START_MINIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoW Settings.
        /// </summary>
        internal static string STRING_SETTING_WOW {
            get {
                return ResourceManager.GetString("STRING_SETTING_WOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string STRING_SHOW_CONFIG {
            get {
                return ResourceManager.GetString("STRING_SHOW_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybinds.
        /// </summary>
        internal static string STRING_SHOW_KEYBINDS {
            get {
                return ResourceManager.GetString("STRING_SHOW_KEYBINDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string STRING_SHOW_PLUGINS {
            get {
                return ResourceManager.GetString("STRING_SHOW_PLUGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string STRING_STATUS {
            get {
                return ResourceManager.GetString("STRING_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string STRING_UPDATE_BUTTON {
            get {
                return ResourceManager.GetString("STRING_UPDATE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update file is being downloaded and will be automatically installed when the download is complete. Please wait....
        /// </summary>
        internal static string STRING_UPDATE_TEXT {
            get {
                return ResourceManager.GetString("STRING_UPDATE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Haptics.
        /// </summary>
        internal static string STRING_WINDOW_ADVANCED_HAPTICS {
            get {
                return ResourceManager.GetString("STRING_WINDOW_ADVANCED_HAPTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft currently running.
        /// </summary>
        internal static string STRING_WOW_WINDOW_FOUND {
            get {
                return ResourceManager.GetString("STRING_WOW_WINDOW_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap USB {
            get {
                object obj = ResourceManager.GetObject("USB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon WoWConsolePort {
            get {
                object obj = ResourceManager.GetObject("WoWConsolePort", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wowmapper3 {
            get {
                object obj = ResourceManager.GetObject("wowmapper3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
